### ISSUE TITLE
Error when processing java version 11.0.20.1

### ISSUE THREAD

**Issue by kasiaMarek** [sourcegraph/sbt-sourcegraph#85]
`Cannot process java.home property, unknown format: [11.0.20.1]`error when trying to read in version of Eclipse Adoptium Java 11.0.20.1 . Full error: https://github.com/scalameta/metals/actions/runs/6110428021/job/16583407524?pr=5626.

**Comment by keynmol** [comment]
Fascinating - seems like the version changed just recently :D https://github.com/scalameta/metals/actions/runs/6097314874/job/16544701050#step:4:11
